config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :appointments
      resources :barbers

      root to: "users#index"
    end
  # devise_for :user
    devise_for :users ,  controllers: {
      sessions: 'users/sessions'
      
    }

    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :users
    resources :barbers
    resources :appointments
    root 'application#home'
    
end

app/models/barber.rb
class Barber < ApplicationRecord
      has_many :appointments
      has_many :users , through: :appointments
end

app/controllers/admin/barbers_controller.rb
module Admin
  class BarbersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/barbers_controller.rb
class BarbersController < ApplicationController
  before_action :set_barber, only: [:show, :edit, :update, :destroy]

  # GET /barbers
  # GET /barbers.json
  def index
    @barbers = Barber.all
  end

  # GET /barbers/1
  # GET /barbers/1.json
  def show
  end

  # GET /barbers/new
  def new
    @barber = Barber.new
  end

  # GET /barbers/1/edit
  def edit
  end

  
  def create
    @barber = Barber.new(barber_params)
      if @barber.save
        redirect_to @barber, notice: 'Barber was successfully created.'
      else
        render :new
      end
    end
  end

  def update
    respond_to do |format|
      if @barber.update(barber_params)
       redirect_to @barber, notice: 'Barber was successfully updated.'
      else
       render json: @barber.errors, status: :unprocessable_entity
      end
    end
  end

  def destroy
    @barber.destroy
     redirect_to barbers_url, notice: 'Barber was successfully destroyed.'
    end
  end

  private

    def set_barber
      @barber = Barber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barber_params
      params.require(:barber).permit(:name, :raing, :phone)
    end
end

app/helpers/barber_helper.rb
module BarberHelper
end

app/views/barbers/_form.html.erb
<%= form_with(model: @barber, local: true) do |form| %>
  

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :raing %>
    <%= form.text_field :raing %>
  </div>
  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/barbers/edit.html.erb
<h1>Editing Barber</h1>

<%= render 'form', barber: @barber %>

<%= link_to 'Show', @barber %> |
<%= link_to 'Back', barbers_path %>

app/views/barbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Barbers</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th>Phone number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @barbers.each do |barber| %>
      <tr>
        <td><%= barber.name %></td>
        <td><%= barber.raing %></td>
        <td><%= barber.phone %></td>
        <td><%= link_to 'Show', barber %></td>
        <td><%= link_to 'Edit', edit_barber_path(barber) %></td>
        <td><%= link_to 'Destroy', barber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New barber', new_barber_path %>

app/views/barbers/new.html.erb
<h1>New Barber</h1>

<%= render 'form'%>

app/views/barbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @barber.name %>
</p>
<p>
  <strong>Rating:</strong>
  <%= @barber.raing %>
</p>
<p>
  <strong>Phone number:</strong>
  <%= @barber.phone %>
</p>

<%= link_to 'Edit', edit_barber_path(@barber) %> |
<%= link_to 'Back', barbers_path %>