config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :appointments
      resources :barbers

      root to: "users#index"
    end
  # devise_for :user
    devise_for :users ,  controllers: {
      sessions: 'users/sessions'
      
    }

    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :users
    resources :barbers
    resources :appointments
    root 'application#home'
    
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :barber
    belongs_to :user
end

app/controllers/admin/appointments_controller.rb
module Admin
  class AppointmentsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

      def index
        puts current_user.name
        puts current_user.id
        @appointments = Appointment.where(user_id: current_user.id) 
      end
    
      def new
        @appointment = Appointment.new
      end

      def show
        @appointment = Appointment.find(params[:id])
      end

      def destroy
        Appointment.find(params[:id]).destroy
          redirect_to appointments_url, notice: 'Appointment was successfully destroyed.'
        end
      
      

      def create
        param=appointment_params.merge :user_id => current_user.id 
        @appointment = Appointment.new(param)
          if @appointment.save
             redirect_to @appointment, notice: 'Appointment was successfully created.' 
          else
            render json: @appointment.errors, status: :unprocessable_entity 
          end
        end
      def edit
        @appointment = Appointment.find(params[:id])
      end

      def update
        appointment = Appointment.find(params[:id])
        appointment.update(params.require(:appointment).permit(:date, :time, :barber_id, :user_id))
        redirect_to appointment
      end
      
      def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date, :time, :barber_id)
    end
    
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
        <% appointment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="w-1/3 max-w-1/3 md:w-1/3 p-6 mx-auto mt-32 border">
			<div class=" bg-white">
					<p class="w-full text-gray-600 text-3xl text-center">Appointment</p>
          <p class="text-center">Date:</p>
					<p class="border-b text-center"><%= f.date_select :date%></p>
          <p class="text-center">Barber:</p>
          <p class="border-b text-center"><%= f.time_select :time%></p>
          <p class="text-center">Customer:</p>
          <p class="border-b text-center"><%= f.select :barber_id, Barber.all.collect { |p| [ p.name, p.id ] } , { label: "Choose your favorite barber:" }, { class: "selectpicker" } %></p>
        <hr>
			</div>
			<div class="flex justify-center mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow p-6">
        <button><%= f.submit %></button>
        
			</div>
		</div>

<% end %>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/index.html.erb
<section class="">
	
	<div class="container flex flex-wrap pt-4 pb-12">
	
		<h1 class="w-full my-2 text-5xl mt-32 font-bold leading-tight text-center text-gray-800">Appointments</h1>
		<div class="w-full mb-4">	
			<div class="h-1 mx-auto gradient w-64 opacity-25 my-0 py-0 rounded-t"></div>
		</div>

    <% @appointments.each do |appointment| %>

		<div class="w-1/3 max-w-1/3 md:w-1/3 p-6 mt-4 border">
		  <div class=" bg-white">
		  <p class="w-full text-gray-600 text-3xl text-center">Appointment</p>
		  <p class="text-center">Date:</p>
		  <p class="border-b text-center"><%= appointment.date %></p>
          <p class="text-center">Barber:</p>
          <p class="border-b text-center"><%= appointment.barber.name %></p>
          <p class="text-center">Customer:</p>
          <p class="border-b text-center"><%= current_user.name %></p>
        <hr>
			</div>
			<div class="flex-none mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow p-6">
				<div class="flex items-center justify-center">
					<button class="mx-auto lg:mx-0 hover:underline bg-green-700 font-bold rounded-full my-6 py-4 px-8 shadow-lg"><%= link_to 'Show', appointment , :class => 'text-white hover:text-white' %></button>
          <button class="mx-auto lg:mx-0 hover:underline bg-yellow-500 font-bold rounded-full my-6 py-4 px-8 shadow-lg"><%= link_to 'Edit', edit_appointment_path(appointment), :class => 'text-white hover:text-white' %></button>
          <button class="mx-auto lg:mx-0 hover:underline bg-red-700 font-bold rounded-full my-6 py-4 px-8 shadow-lg"><%= link_to 'destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'text-white hover:text-white' %></button>
				</div>
			</div>
		</div>
  <% end %>
	</div>
  <div class="container flex justify-center">
  <button class="m-auto text-center lg:mx-0 hover:underline newApp font-bold rounded-full my-6 py-4 px-8 shadow-lg"><%= link_to 'New Appointment', new_appointment_path,:class => 'text-white' %></button>
  </div>
    
</section>

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>


<div class="w-1/3 max-w-1/3 md:w-1/3 p-6 mx-auto mt-32 border">
			<div class=" bg-white">
					<p class="w-full text-gray-600 text-3xl text-center">Appointment</p>
          <p class="text-center">Date:</p>
					<p class="border-b text-center"><%= current_user.name %></p>
          <p class="text-center">Barber:</p>
          <p class="border-b text-center"><%= @appointment.date %></p>
          <p class="text-center">Customer:</p>
          <p class="border-b text-center"><%= @appointment.time %></p>
        <hr>
			</div>
			<div class="flex justify-center mt-auto bg-white rounded-b rounded-t-none overflow-hidden shadow p-6">
        <button class="mx-auto lg:mx-0 hover:underline bg-green-700 font-bold rounded-full my-6 py-4 px-8 shadow-lg"><%= link_to 'Edit', edit_appointment_path(@appointment) %></button>
        <button class="mx-auto lg:mx-0 hover:underline bg-yellow-500 font-bold rounded-full my-6 py-4 px-8 shadow-lg"><%= link_to 'Back', appointments_path %></button>
			</div>
		</div>