config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :appointments
      resources :barbers

      root to: "users#index"
    end
  # devise_for :user
    devise_for :users ,  controllers: {
      sessions: 'users/sessions'
      
    }

    
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :users
    resources :barbers
    resources :appointments
    root 'application#home'
    
end

app/views/layouts/_nav.html.erb
<nav id="header" class="fixed w-full z-30 top-0 navc">

	<div class="w-full container mx-auto flex flex-wrap items-center justify-between mt-0 py-2">
			
		<div class="pl-4 flex items-center">
			<a class="toggleColour text-white no-underline hover:no-underline font-bold text-2xl lg:text-4xl"  href="#"> 
				<!--Icon from: http://www.potlabicons.com/ -->
				 Barber Shop
			</a>
		</div>

		<div class="block lg:hidden pr-4">
			<button id="nav-toggle" class="flex items-center p-1 text-orange-800 hover:text-gray-900">
				<svg class="fill-current h-6 w-6" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
			</button>
		</div>

		<div class="w-full flex-grow lg:flex lg:items-center lg:w-auto lg:block mt-2 lg:mt-0  lg:bg-transparent text-black p-4 lg:p-0 z-20" id="nav-content">
			<ul class="list-reset mt-4 lg:flex justify-end flex-1 items-center">
				<%# <% if user_id == 1? %> 
				<%# <li class="mr-3"> %>
					<%# <%= link_to 'Admin dashboard',  admin_root  , :class => 'mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full mt-4 lg:mt-0 py-4 px-8 shadow opacity-75' %> 
				<%# </li> %>
				<%# <% end %> 
				<% if current_user and current_user.id == 7%>
				<li class="mr-3">
				<%= link_to 'Admin dashboard',  admin_root_url , :class => ' hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg' %>
				</li>
				<% end%>
				<% unless user_signed_in? %>
				<li class="mr-3">
					<%= link_to 'Login',  new_user_session_path  , :class => 'hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg' %>
				</li> 
				<li class="mr-3"> 
					<%= link_to 'Register',  new_user_registration_path , :class => 'hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg' %>
				</li>
				<% else %>
				<li class="mr-3">
					<%= link_to 'Appointments',  appointments_path  , :class => 'hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg' %>
				</li> 
				<li class="mr-3">
					<%= link_to 'Account',  edit_user_registration_path  , :class => 'hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg' %>
				</li> 
				<%# <li class="mr-3">  %>
					<%# <%= link_to 'edit',  edit_user_registration_path , method: :edit , :class => 'mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full mt-4 lg:mt-0 py-4 px-8 shadow opacity-75' %>
				<%# </li> %>
				<li class="mr-3">
          			<%= link_to 'logout', destroy_user_session_path , method: :delete , :class => 'hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg' %>
				</li>
				<% end %>
			</ul>
		</div>
	</div>


	
	
	<hr class="border-b border-gray-100 opacity-25 my-0 py-0" />
</nav>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Tailwind Starter Template - Landing Page Template: Tailwind Toolbox</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
		/* EFEEFE
		6C62FF */
		.newApp {
			background: #6C62FF;
		}
		.navc {
		background:	linear-gradient(90deg, #6C62FF 40%, #EFEEFE 140%);
		}
		.gradient { 
	  	background: linear-gradient(90deg, #6C62FF 40%, #EFEEFE 140%);
	  	background-attachment: fixed;
		/* background-image: url(https://images.squarespace-cdn.com/content/v1/543cf49ee4b0451fa8a5273c/1473781565057-09MA2IGSH5E56B5FUI54/ke17ZwdGBToddI8pDm48kOggE0Ch6pMGalwtLMqzsSB7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z5QPOohDIaIeljMHgDF5CVlOqpeNLcJ80NK65_fV7S1Ufo5RWkg_J4of0jUNHaDHx6pZKBvpVYzidBWCapg0tuoMuEaB2HPGSYDV-11UTcW2g/13923649_1749363545275198_3943147010150863759_o.jpg); */

		}
	</style> 

  </head>

  <body>
    
      <%= render 'layouts/nav' %>
      
        <%= yield %>
      
      <script>

	var scrollpos = window.scrollY;
	var header = document.getElementById("header");
	var navcontent = document.getElementById("nav-content");
	var navaction = document.getElementById("navAction");
	var brandname = document.getElementById("brandname");
	var toToggle = document.querySelectorAll(".toggleColour");

	document.addEventListener('scroll', function() {

	/*Apply classes for slide in bar*/
	scrollpos = window.scrollY;

    if(scrollpos > 10){
      header.classList.add("bg-white");
	  navaction.classList.remove("bg-white");
	  navaction.classList.add("gradient");
	  navaction.classList.remove("text-gray-800");
	  navaction.classList.add("text-white");
	  //Use to switch toggleColour colours
  	  for (var i = 0; i < toToggle.length; i++) {
	     toToggle[i].classList.add("text-gray-800");
		 toToggle[i].classList.remove("text-white");
	  }
	  header.classList.add("shadow");
	  navcontent.classList.remove("bg-gray-100");
	  navcontent.classList.add("bg-white");
    }
    else {
	  header.classList.remove("bg-white");
	  navaction.classList.remove("gradient");
	  navaction.classList.add("bg-white");
	  navaction.classList.remove("text-white");
	  navaction.classList.add("text-gray-800");
	  //Use to switch toggleColour colours
  	  for (var i = 0; i < toToggle.length; i++) {
	     toToggle[i].classList.add("text-white");
		 toToggle[i].classList.remove("text-gray-800");
	  }
	  
	  header.classList.remove("shadow");
	  navcontent.classList.remove("bg-white");
	  navcontent.classList.add("bg-gray-100");
	  
    }

	});

	
</script>

<script>
	
	
	/*Toggle dropdown list*/
	/*https://gist.github.com/slavapas/593e8e50cf4cc16ac972afcbad4f70c8*/
	
	var navMenuDiv = document.getElementById("nav-content");
	var navMenu = document.getElementById("nav-toggle");
	
	document.onclick = check;
	function check(e){
	  var target = (e && e.target) || (event && event.srcElement);
	  
	  //Nav Menu
	  if (!checkParent(target, navMenuDiv)) {
		// click NOT on the menu
		if (checkParent(target, navMenu)) {
		  // click on the link
		  if (navMenuDiv.classList.contains("hidden")) {
			navMenuDiv.classList.remove("hidden");
		  } else {navMenuDiv.classList.add("hidden");}
		} else {
		  // click both outside link and outside menu, hide menu
		  navMenuDiv.classList.add("hidden");
		}
	  }
	  
	}
	function checkParent(t, elm) {
	  while(t.parentNode) {
		if( t == elm ) {return true;}
		t = t.parentNode;
	  }
	  return false;
	}
</script>
  </body>
</html>